### ISSUE TITLE
Allow upload to be started with a custom event (or form submit)

### ISSUE THREAD

**Issue by bondt** [shammelburg/ng-simple-upload#1]
The upload is triggered on change at the moment. For some (like myself) it is easier to allow the user to upload manually, for security reasons.

**Comment by shammelburg** [comment]
Thank you for your comment. I will create a code snippet where you can submit the upload manually.

**Comment by shammelburg** [comment]
I have amended the directive to allow it to be triggered on button click.

**Comment by bondt** [comment]
Thanks!
